FROM python:3.8.3-alpine

# set work directory
WORKDIR /home/pusa26/Desktop/Work\ And\ Stuffs/Operating\ Baba/E-Water-Station-System/eWater_backend
# set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# install dependencies
RUN pip install --upgrade pip
RUN ls -a 
RUN pip install -r requirements.txt

# copy project
COPY . /home/pusa26/Desktop/Work\ And\ Stuffs/Operating\ Baba/E-Water-Station-System/eWater_backend

EXPOSE 8000

CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
