# Generated by Django 3.2.8 on 2022-02-08 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(default='', max_length=11)),
                ('fullname', models.CharField(default='', max_length=50)),
                ('address', models.CharField(default='', max_length=50)),
                ('email', models.CharField(default='', max_length=30)),
                ('verified', models.BooleanField(default=False)),
                ('dumm', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='OrderData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(default='', max_length=11)),
                ('fullname', models.CharField(default='', max_length=50)),
                ('address', models.CharField(default='', max_length=50)),
                ('item', models.PositiveSmallIntegerField(choices=[(4, '500ml bottled water'), (5, '350ml bottled water'), (3, 'Half gallon'), (2, '1 Gallon (for despenser)'), (1, '1 Gallon (with faucet)')], default=1)),
                ('pendingPayment', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('Paid', models.BooleanField(default=False)),
                ('Delivered', models.BooleanField(default=False)),
                ('reservationDate', models.DateTimeField()),
            ],
        ),
    ]
