# Generated by Django 3.2.8 on 2022-02-08 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EWater_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdata',
            name='item',
            field=models.PositiveSmallIntegerField(choices=[(5, '350ml bottled water'), (4, '500ml bottled water'), (2, '1 Gallon (for despenser)'), (1, '1 Gallon (with faucet)'), (3, 'Half gallon')], default=1),
        ),
    ]
