# Generated by Django 3.2.8 on 2022-02-08 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EWater_api', '0004_alter_orderdata_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdata',
            name='item',
            field=models.PositiveSmallIntegerField(choices=[(4, '500ml bottled water'), (2, '1 Gallon (for despenser)'), (3, 'Half gallon'), (1, '1 Gallon (with faucet)'), (5, '350ml bottled water')], default=1),
        ),
    ]
