# Generated by Django 3.2.8 on 2022-02-09 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EWater_api', '0006_alter_orderdata_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientdata',
            name='dumm',
        ),
        migrations.AlterField(
            model_name='orderdata',
            name='item',
            field=models.PositiveSmallIntegerField(choices=[(5, '350ml bottled water'), (1, '1 Gallon (with faucet)'), (4, '500ml bottled water'), (3, 'Half gallon'), (2, '1 Gallon (for despenser)')], default=1),
        ),
    ]
