# Generated by Django 3.2.8 on 2022-01-02 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EWater_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tutorial',
            new_name='ClientData',
        ),
    ]
